import { SimilarImagesProps } from "./model";
import classes from "./similar-images.module.scss";
import ImageButton from "../image-button/image-button";

export default function SimilarImages({ images }: SimilarImagesProps) {
  return (
    <div className={classes.Container}>
      <span className={classes.Title}>
        Similar images generated by other users
      </span>

      <div className={classes.ImageWrapper}>
        {images.map((image, index) => (
          <ImageButton key={index} size="small" src={image} />
        ))}
      </div>
    </div>
  );
}
